import type { Metadata } from "next";
import "./globals.css";

import { Inter } from "next/font/google";
const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "KuendaBooka",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-ao">
      <body className={`antialiased theme-custom ${font.className}`}>
        <div>{children}</div>
      </body>
    </html>
  );
}
